---
- name: Install snmpd
  apt: pkg=snmpd state=installed update_cache=true
  register: snmpdinstalled
  notify:
    - Start SNMP Agent

- name: Add snmpd.conf
  when: snmpdinstalled|success
  copy: src=snmpd.conf dest=/etc/snmp owner=root group=root
  notify:
    - Restart SNMP Agent

- name: Allow SNMP Agent in UFW
  when: snmpdinstalled|success
  copy: src=snmpd dest=/etc/ufw/applications.d owner=root group=root
  notify:
    - Allow SNMP Agent in UFW
