---
docker_package: "docker-ce"
volume_group_name: "containers"
physical_volumes_devices: "/dev/sdb"
logical_volume_name: "docker"
logical_volume_size: "5G"
filesystem_type: "xfs"
filesystem_options: "noatime,relatime"
docker_tcp_port: "2376"
