---
- name: Install typical packages
  tags:
    - install_typical_packages
  become: yes
  apt:
    name: "{{ _package }}"
    update_cache: yes
    autoclean: yes
  with_items: "{{ debian_typical_packages }}"
  loop_control:
    loop_var: _package
