---
- name: Adding forwarding proxy configuration to shell
  tags:
    - adding_shell_proxy_env
  become: yes
  template:
    src:  "{{ profile_proxyenv_file }}"
    dest: "{{ profile_proxyenv_fqp }}"
    owner: root
    group: root
    mode: 0644
