---
- name: Install ufw
  tags:
    - install_ufw
  become: yes
  apt:
    name: ufw
    update_cache: yes
    autoclean: yes

- name:
  tags:
    - allow_openssh_ufw
  become: yes
  ufw:
    name: OpenSSH
    state: enabled
