---
- import_tasks: add-proxy-env.yml
- import_tasks: ca-certificates.yml
- import_tasks: server-certificates.yml
- import_tasks: install-ufw.yml
- import_tasks: install-typical-packages.yml
- import_tasks: install-monitoring-packages.yml
- import_tasks: install-vm-open-tools.yml
  when: ansible_virtualization_type == "VMware"

