---
- name: Clearing /var/lib/kubelet/
  tags:
    - clear_kubelet_dir
  become: yes
  file:
    path: "/var/lib/kubelet/*"

- name: Join Kubernetes clusterr
  tags:
    - join_kubernetes_cluster
  become: yes
  command: "{{ kubeadm_join }}"
