---
- name: Running tasks specific to Kubernetes worker nodes
  block:
  - name: Updating forwarding proxy configuration to shell
    tags:
      - update_shell_proxy_env
      - set-k8s-master-ip
    become: yes
    lineinfile:
      line: 'no_proxy="{{ no_proxy }},{{ kubernetes_master_ip }}"'
      path: "{{ profile_proxyenv_fqp }}"
      regexp: "^no_proxy="

  - name: Reset kubelet configuration
    tags:
      - clear_kubelet_dir
    become: yes
    command: kubeadm reset

  - name: Join Kubernetes clusterr
    tags:
      - join_kubernetes_cluster
    become: yes
    shell: "{{ kubeadm_join }}"
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }},{{ kubernetes_master_ip }}"
  when: k8s_type != "master"
