---
- block:
  - name: Check if master is already initialized
    tags:
      - test
      - check_if_initialized
    stat:
      path: /etc/kubernetes/admin.conf
    register: _admin_config

  - block:
    - name: Initializing master (THIS IS GOING TO TAKE A WHILE)
      tags:
        - test
        - create_k8s_mastger
      become: yes
      command: "kubeadm init --pod-network-cidr=10.244.0.0/16"
      register: _kubeadm_init
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"
        no_proxy: "{{ no_proxy }},{{ ansible_default_ipv4.address }}"

    - name: Write kubeadm init output to file
      tags:
        - write_kubeadmin_init_output
      become: yes
      lineinfile:
        create: yes
        path: "{{ kubeadm_init_output_fqp }}"
        line: "{{ line }}"
      with_items: "{{ _kubeadm_init.stdout_lines }}"
      loop_control:
        loop_var: line
    when: not _admin_config.stat.exists

  - name: Read kubeadm init output
    tags:
      - test
    become: yes
    command: "cat {{ kubeadm_init_output_fqp }}"
    register: _kubeadm_init_output

  - name: Register kubeadm join command
    tags:
      - test
    set_fact:
      kubeadm_join: "{{ line | regex_replace ('^.\\s')}}"
    with_items: "{{ _kubeadm_init_output.stdout_lines }}"
    loop_control:
      loop_var: line
    when: line | regex_search('kubeadm join')

  - name: "Create user's kubernetes configuration directory"
    tags:
      - create_user_kube_dir
    file:
      path: "{{ ansible_user_dir }}/.kube"
      state: directory

  - name: Copy admin.conf to user configuration directory
    tags:
      - copy_admin_conf
    become: yes
    command: "cp -f /etc/kubernetes/admin.conf {{ ansible_user_dir }}/.kube/config"

  - name: Change permissions of user configuration file
    tags:
      - change_permissions_of_user_conf
    become: yes
    file:
      path: "{{ ansible_user_dir }}/.kube/config"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_real_group_id }}"
      mode: "0640"

  - name: Add KUBECONFIG to .profile
    tags:
      - add_kubeconfig_to_profile
    lineinfile:
      path: "{{ ansible_user_dir }}/.profile"
      line: "export KUBECONFIG=$HOME/.kube/config"
      state: present

  - name: "Install {{ k8s_network_solution_name }} networking solution for pod networks"
    tags:
      - install_k8s_network
    shell: "kubectl apply -f {{ k8s_network_solution_url }}"
    environment:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy: "{{ no_proxy }},{{ ansible_default_ipv4.address }}"
  when: k8s_type == "master"
