---

- name: "Download {{ installer_archive }} MD5 sum"
  tags:
    - download-md5
  get_url:
    dest: "{{ download_directory_path }}/{{ installer_archive }}.md5"
    mode: 0644
    tmp_dest: "{{ temporate_download_directory_path }}/"
    url: "{{ unarchive_src }}.md5"
    validate_certs: false
  delegate_to: localhost

- name: "Download {{ installer_archive }}"
  tags:
    - download
  get_url:
    checksum:  "md5:{{ _md5sum }}"
    dest: "{{ download_directory_path }}/{{ installer_archive }}"
    mode: 0644
    tmp_dest: "{{ temporate_download_directory_path }}/"
    url: "{{ unarchive_src }}"
    validate_certs: false
  vars:
    _md5sum: "{{ lookup('file', '{{ download_directory_path }}/{{ installer_archive }}.md5') }}"
  delegate_to: localhost
