---
- when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  block:
    - name: update sources.list
      tags:
        - update_debian_sources
      become: yes
      copy:
        src: "{{ item }}"
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
      with_items:
        - "{{ sources[ansible_distribution] }}"
      register: sourceupdate

    - name: update 99proxy
      tags:
        - update_proxy
      become: yes
      template:
        src: "{{ item }}"
        dest: /etc/apt/apt.conf.d/99proxy
        owner: root
        group: root
        mode: 0644
      with_items:
        - "99proxy.j2"

    - name: install aptitude
      tags:
        - install_aptitude
      become: yes
      apt:
        name: aptitude
        update_cache: yes
        autoclean: yes

    - name: upgrade packages
      tags:
        - upgrade
      become: yes
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes
        purge: yes

