---
- name: update sources.list
  tags:
    - update_debian_sources
  become: yes
  template:
    src: "{{ sources[ansible_distribution] }}.j2"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: update 99proxy
  tags:
    - update_proxy
  become: yes
  template:
    src: "99proxy.j2"
    dest: /etc/apt/apt.conf.d/99proxy
    owner: root
    group: root
    mode: 0644

- name: upgrade packages
  tags:
    - upgrade
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    force_apt_get: yes
    purge: yes
    update_cache: yes
    upgrade: dist
