---
- block:
  - name: Install heapster monitoring
    tags:
      - install-k8s-heapster
    shell: "kubectl create -f {{ _url }}"
    with_items:
      - "{{ kubernetes_heapster_urls }}"
    loop_control:
      loop_var: _url

  - name: Install Kubernetes Dashboard
    tags:
      - install-k8s-dashboard
    shell: "kubectl apply -f {{ _url }}"
    with_items:
      - "{{ kubernetes_dashboard_urls }}"
    loop_control:
      loop_var: _url

  - name: Start kubernetes proxy
    tags:
      - start-k8s-proxy
    shell: "kubectl proxy"
  when: k8s_type == "master"
